### ISSUE TITLE
creating wallet broken

### ISSUE THREAD

**Issue by lisandroiraguen** [nothingalike/lift-wallet#66]
@@@ walletsPath, network, name /zfs-pool/home/rcmorano/Projects/lift-wallet-clean/cardano/wallets testnet ada-and-a-half
get phrase
adding wallet {
  name: 'stake1',
  mnemonic: 'remain fine razor curious target benefit juice merit corn coffee elbow shaft program ranch teach matter high leader young subject hundred already page come',
  passphrase: '1234567890',
  network: 'testnet'
}
(node:1933090) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1933090) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.resolve (path.js:980:7)
    at getAddresses (webpack:///./src/services/wallet.service.js?:246:67)
    at IpcMainImpl.eval (webpack:///./src/background.js?:167:107)
    at IpcMainImpl.emit (events.js:223:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:173:8161)
    at WebContents.emit (events.js:223:5)
(node:1933090) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
@@@ walletsPath, network, name /zfs-pool/home/rcmorano/Projects/lift-wallet-clean/cardano/wallets testnet undefined

**Comment by lisandroiraguen** [comment]
is solved
